Payroll.UI.Web/Controllers/PayrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using ClosedXML;
using ClosedXML.Excel;
using Payroll.Domain.Interfaces.Domain;

namespace Payroll.UI.Web.Controllers
{
    [Authorize]
    public class PayrollController : Controller
    {
        private IPayrollServiceDomain _payrollRepository;

        public PayrollController(IPayrollServiceDomain payrollRepository)
        {
            _payrollRepository = payrollRepository;
        }
        
        [HttpPost]
        public ActionResult CommitToPayroll(FormCollection collection)
        {
            string Date = collection.Get("date");
            DateTime date;
            if (Date == null)
            {
                date = DateTime.Now;
            }
            else
            {
                int day = Convert.ToInt32(Date.Split('.')[0]);
                int month = Convert.ToInt32(Date.Split('.')[1]);
                int year = Convert.ToInt32(Date.Split('.')[2]);
                date = new DateTime(year, month, day);
            }
            Payroll.Domain.Entities.Payroll Payroll = _payrollRepository.CommitToPayroll(date);
            return RedirectToAction("Index", new { id = Payroll.Id });
        }

        // GET: Payroll
        [HttpGet]
        public ActionResult Index(int id)
        {
            var items = _payrollRepository.GetItemsByPayrollId(id);
            DateTime date = new DateTime(items.FirstOrDefault().Payroll.Year, items.FirstOrDefault().Payroll.Month,1);
            ViewBag.Date = date;
            return View(items);
        }

        [HttpPost]
        public ActionResult ExportPayrollToExcel(FormCollection collection)
        {
            int payrollId = Convert.ToInt32(collection.Get("payrollId"));
            var items = _payrollRepository.GetItemsByPayrollId(payrollId);

            var date = new DateTime(items.FirstOrDefault().Payroll.Year, items.FirstOrDefault().Payroll.Month, 1);

            var dt = new DataTable();
            dt.Columns.Add("Emp ID", typeof(string));
            dt.Columns.Add("Full Name", typeof(string));
            dt.Columns.Add("Normal", typeof(decimal));
            dt.Columns.Add("Overtime (x1.33)", typeof(decimal));
            dt.Columns.Add("Overtime (x1.5)", typeof(decimal));
            dt.Columns.Add("Overtime (x2)", typeof(decimal));
            dt.Columns.Add("Effective Hours", typeof(decimal));
            dt.Columns.Add("Rate (R/Hr)", typeof(decimal));
            dt.Columns.Add("Amount (Gross)", typeof(decimal));
            dt.Columns.Add("Amount (Taxable)", typeof(decimal));            
            dt.Columns.Add("Bonus", typeof(decimal));
            dt.Columns.Add("Gross Wages", typeof(decimal));
            dt.Columns.Add("G/Tax", typeof(decimal));
            dt.Columns.Add("PAYE", typeof(decimal));
            dt.Columns.Add("SNPF Employee", typeof(decimal));
            dt.Columns.Add("SNPF Employer", typeof(decimal));
            dt.Columns.Add("Amount (Net)", typeof(decimal));
            dt.Columns.Add("Loan (Deduct)", typeof(decimal));
            dt.Columns.Add("Advance (Add)", typeof(decimal));
            dt.Columns.Add("Amount Paid", typeof(decimal));

            foreach(var x in items)
            {
                var contract = x.Employee.Contracts.Where(t => t.ExpiryDate > DateTime.Now).FirstOrDefault();
                if (contract.Waged)
                {
                    dt.Rows.Add(
                    x.Employee.EmpId,
                    x.Employee.FullName,
                    x.NormalHours,
                    x.TimeOneThirdHours,
                    x.TimeOneHalfHours,
                    x.DoubleTimeHours,
                    x.EffectiveHours,
                    contract.Wage,
                    x.AmountGross,
                    x.AmountTaxable,
                    x.Bonus,
                    x.Gross_Wage,
                    x.General_Tax,
                    x.PAYE,
                    x.SNPF_Employee,
                    x.SNPF_Employer,
                    x.Amount_Net,
                    x.Loan,
                    x.Advance,
                    x.Amount_Paid
                    );
                }
                else
                {
                    dt.Rows.Add(
                   x.Employee.EmpId,
                   x.Employee.FullName,
                   0,
                   0,
                   0,
                   0,
                   0,
                   contract.Salary,
                   x.AmountGross,
                   x.AmountTaxable,
                   x.Bonus,
                   x.Gross_Wage,
                   x.General_Tax,
                   x.PAYE,
                   x.SNPF_Employee,
                   x.SNPF_Employer,
                   x.Amount_Net,
                   x.Loan,
                   x.Advance,
                   x.Amount_Paid
                   );
                }
                
            }
            dt.TableName = "Payroll";
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                
                wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                wb.Style.Font.Bold = true;

                Response.Clear();
                Response.Buffer = true;
                Response.Charset = "";
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment;filename= Payroll_" + date.ToString("MMM_yyyy") + ".xlsx");

                using (MemoryStream MyMemoryStream = new MemoryStream())
                {
                    wb.SaveAs(MyMemoryStream);
                    MyMemoryStream.WriteTo(Response.OutputStream);
                    Response.Flush();
                    Response.End();
                }
            }


            return RedirectToAction("Index", "Payroll", new { id = 1 });
        }
    }
}

Payroll.UI.Web/Controllers/PayrollItemController.cs
using Payroll.Domain.Entities;
using Payroll.Domain.Interfaces.Domain;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Payroll.UI.Web.Controllers
{
    [Authorize]
    public class PayrollItemController : Controller
    {
        private IPayrollItemServiceDomain _serviceDomain;

        public PayrollItemController(IPayrollItemServiceDomain serviceDomain)
        {
            _serviceDomain = serviceDomain;
        }

        // GET: PayrollItem
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UpdatePayroll(FormCollection collection)
        {
            string bonusString = collection.Get("bonusVal");
            string loanString = collection.Get("loanVal");
            string advanceString = collection.Get("advanceVal");
            decimal bonus = Convert.ToDecimal(bonusString,CultureInfo.InvariantCulture);
            decimal loan = Convert.ToDecimal(loanString, CultureInfo.InvariantCulture);
            decimal advance = Convert.ToDecimal(advanceString, CultureInfo.InvariantCulture);
            int payrollItemId = Convert.ToInt32(collection.Get("payrollVal"));
            var item = _serviceDomain.GetItem(payrollItemId);
            item.Loan = loan;
            item.Advance = advance;
            item.Bonus = bonus;
            _serviceDomain.UpdateItem(item);

            return RedirectToAction("Index", "Payroll", new { id = item.PayrollId });
        }       
    }
    internal class TaxBand
    {
        public double MarginalRate { get; set; }
        public double BaseAmount { get; set; }
        public double Threshold { get; set; }
        public double Limit { get; set; }
    }
}

Payroll.UI.Web/Views/Payroll/Index.cshtml
@using Payroll.Domain
@model List<Payroll.Domain.Entities.PayrollItem>
@{
    DateTime date = ViewBag.Date;
    ViewBag.Title = date.ToString("MMM, yy") + " Payroll";
    ViewBag.ViewHeader = "Payroll";
    ViewBag.Description = date.ToString("MMMM, yyyy");
    ViewBag.Controller = "Payroll";
    ViewBag.Action = "Index";
}
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Emp ID</th>
                            <th>Full Name</th>
                            <th>Normal</th>
                            <th>Overtime (x1.33)</th>
                            <th>Overtime (x1.5)</th>
                            <th>Overtime (x2)</th>
                            <th>Time Effective</th>
                            <th>Rate</th>
                            <th>Amount (Gross)</th>
                            <th>Amount (Taxable)</th>
                            <th>Bonus</th>
                            <th>Gross Wages</th>
                            <th>G / Tax</th>
                            <th>PAYE</th>
                            <th>SNPF (Employee)</th>
                            <th>SNPF (Employer)</th>
                            <th>Amount (Net)</th>
                            <th>Loan</th>
                            <th>Advance</th>
                            <th>Amount Paid</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            var contract = item.Employee.Contracts.Where(p => p.ExpiryDate > DateTime.Now).FirstOrDefault();
                            <tr>
                                @using (Html.BeginForm("UpdatePayroll", "PayrollItem", FormMethod.Post))
                                {                                    
                                    <td>@item.Employee.EmpId</td>
                                    <td>@(item.Employee.LastName + ", " + item.Employee.FirstName)</td>
                                    if (contract.Salaried)
                                    {
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>@contract.Salary.ToString("C2")</td>
                                    }
                                    else
                                    {
                                        <td>@item.NormalHours.ToString("F2")</td>
                                        <td>@item.TimeOneThirdHours.ToString("F2")</td>
                                        <td>@item.TimeOneHalfHours.ToString("F2")</td>
                                        <td>@item.DoubleTimeHours.ToString("F2")</td>
                                        <td>@item.EffectiveHours.ToString("F2")</td>
                                        <td>@contract.Wage.ToString("C2")</td>
                                    }
                                    <td>@item.AmountGross.ToString("C2")</td>
                                    <td>@item.AmountTaxable.ToString("C2")</td>
                                    <td>
                                        <span style="white-space:nowrap"><label>R</label><input type="number" step="0.5" value="@item.Bonus.ToString("F2").Replace(',','.')" name="bonusVal" id="bonusVal" class="form-control" style="width:100px;margin-left:5px;" /></span>
                                    </td>
                                    <td>@item.Gross_Wage.ToString("C2")</td>
                                    <td>@item.General_Tax.ToString("C2")</td>
                                    <td>@item.PAYE.ToString("C2")</td>
                                    <td>@item.SNPF_Employee.ToString("C2")</td>
                                    <td>@item.SNPF_Employer.ToString("C2")</td>
                                    <td>@item.Amount_Net.ToString("C2")</td>
                                    <td>
                                        <span style="white-space:nowrap"><label>R</label><input type="number" step="0.5" value="@item.Loan.ToString("F2").Replace(',','.')" name="loanVal" id="loanVal" class="form-control" style="width:100px;margin-left:5px;" /></span></td>
                                    <td>
                                        <input type="hidden" value="@item.Id" name="payrollVal" id="payrollVal"/>
                                       <span style="white-space:nowrap"><label>R</label><input type="number" step="0.5" value="@item.Advance.ToString("F2").Replace(',','.')" name="advanceVal" id="advanceVal" class="form-control" style="width:100px;margin-left:5px;" /></span> 
                                    </td>
                                    <td>@item.Amount_Paid.ToString("C2")</td>
                                    <td>
                                        <button type="submit" value="Update" class="btn-flat btn-success" style="width:30px;height:24px;border-radius:12px;"><i class="fa fa-check"></i></button>
                                    </td>
                                }                                
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
               @using (Html.BeginForm("ExportPayrollToExcel", "Payroll", FormMethod.Post))
               {
                   <input type="hidden" value="@Model.FirstOrDefault().PayrollId" name="payrollId"/>
                   <button type="submit" class="btn btn-flat btn-success"><i class="fa fa-file-excel-o"></i></button>
               }
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script src="~/Content/js/plugins/DataTables/jquery.dataTables.min.js"></script>
<script src="~/Content/js/plugins/DataTables/dataTables.bootstrap.min.js"></script> 
    <script>
        $(function () {
            $('#example1').DataTable({
                "scrollX": true,
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true
            });
        });
    </script>
}